// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS6GG1wcC3hFRhdLNRNA-WRqDWev3oAHE',
    appId: '1:330684126054:web:b6733b1cba7bc59610aea7',
    messagingSenderId: '330684126054',
    projectId: 'anu-timetable',
    authDomain: 'anu-timetable.firebaseapp.com',
    storageBucket: 'anu-timetable.firebasestorage.app',
    measurementId: 'G-N1JL6N5SBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI1DDGLKijqPyUhMFW0iHUza5RVZIrpT0',
    appId: '1:330684126054:android:a2f1e7af1b40ae1910aea7',
    messagingSenderId: '330684126054',
    projectId: 'anu-timetable',
    storageBucket: 'anu-timetable.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqGJkSZ2lypo3PkXLSzpywemqYYOPLcSQ',
    appId: '1:330684126054:ios:2cf38c7014cdc97810aea7',
    messagingSenderId: '330684126054',
    projectId: 'anu-timetable',
    storageBucket: 'anu-timetable.firebasestorage.app',
    iosBundleId: 'com.example.anuTimetable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqGJkSZ2lypo3PkXLSzpywemqYYOPLcSQ',
    appId: '1:330684126054:ios:2cf38c7014cdc97810aea7',
    messagingSenderId: '330684126054',
    projectId: 'anu-timetable',
    storageBucket: 'anu-timetable.firebasestorage.app',
    iosBundleId: 'com.example.anuTimetable',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkbNgBUH_jYhM0RDiMs7SpKJwP1D1mFmM',
    appId: '1:330684126054:web:160525369a2db67910aea7',
    messagingSenderId: '330684126054',
    projectId: 'anu-timetable',
    authDomain: 'anu-timetable.firebaseapp.com',
    storageBucket: 'anu-timetable.firebasestorage.app',
    measurementId: 'G-MRKG8S3S7T',
  );
}
